[SDK-566] Change ApiService module tests
d4l-data4life/hc-sdk-kmp pull request #132
Opened 2021-05-10 13:42 UTC by bitPogo

## Description

This adds a rewritten version of the ApiService module tests. This is part of [SDK-566](https://gesundheitscloud.atlassian.net/browse/SDK-566) and depends on #131.

## Motivation and Context

Currently the ApiService module tests are not working and being in bad shape, so they needed maintenance.

## How is it being implemented?

It adds a fresh written module tests for the ApiService.

## How Has This Been Tested?

This is about tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the changelog accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-05-10 13:46 UTC, bitPogo commented on sdk-core/src/test/java/care/data4life/sdk/network/ApiServiceModuleTest.kt
> +    }
I just want make obvious, that this should work, but it does not. I even not see, why `deleteDocument` has to be different then `deleteRecord` in terms of returning a Completable. Can we align `deleteDocument` and `deleteRecord` so they working similar?

2021-05-12 13:06 UTC, wmontwe requested changes

2021-05-12 13:06 UTC, wmontwe commented on sdk-core/src/test/java/care/data4life/sdk/network/ApiServiceModuleTest.kt
> +        every { env.getApiBaseURL(any()) } returns "https://www.i-hate-fat-constructors.com"
this should be example.com

2021-05-12 13:34 UTC, bitPogo commented on sdk-core/src/test/java/care/data4life/sdk/network/ApiServiceModuleTest.kt
> +        every { env.getApiBaseURL(any()) } returns "https://www.i-hate-fat-constructors.com"
done

2021-05-17 07:32 UTC, wmontwe approved these changes
👍

2021-05-17 07:32 UTC, merged